# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 931036e78592469c376361d7d3318b5154f0871e44177acf5acb13bef187f8f2e3fc9f2af2d6c85112bb42d5260f96abc931a286732b610a3206922acf1565df

test:
  secret_key_base: 2e72474dfb4141a622b3486f4f19b71c7b18a74aef3763eb8e1a5ca8a0098e3ff74530ffe708b6b00b4b41d63ef33f8c6c27c491ceafe00d2947f2f89b13ea3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
